name: sillyhouseorg
description: Safe Social platform for kids

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # main
  http: 0.13.4
  flutter_bloc: ^8.0.1
  dio: 4.0.4
  hydrated_bloc: 8.1.0
  shared_preferences:
  path_provider: 2.0.8
  path: ^1.6.4
  firebase_core: ^1.15.0
  firebase_analytics: ^9.3.1
  intl: ^0.15.8
  uuid: 3.0.5
  package_info: 2.0.2
  flutter_launcher_icons: ^0.10.0

  # ui
  cupertino_icons: 1.0.4
  google_fonts: 2.1.0
  flutter_svg: 0.23.0+1
  carousel_slider: 4.0.0
  another_flushbar: ^1.10.28
  shimmer: ^2.0.0
#  provider: 6.0.1   #remove
#  get_it: 7.2.0     #remove


  # media
  pod_player: ^0.1.0
  video_player: 2.4.5
  cached_network_image: 3.2.0
  camera: ^0.9.4+5
  exif: ^3.1.2      #for camera package fix flipping
#  image_picker: 0.8.4+4
  images_picker: ^1.2.11
  flutter_image_compress: ^1.1.0
  video_compress: 3.1.0
  flutter_stories: ^0.3.1
  # path


dev_dependencies:
  cloud_firestore:
  flutter_test:
    sdk: flutter
  firebase_storage:
  flutter_app_name: ^0.1.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: NunitoSans
      fonts:
        - asset: lib/assets/fonts/NunitoSans-Regular.ttf
        - asset: lib/assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NunitoSans-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/

module:
  androidX: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"

flutter_app_name:
  name: "Silly House"